### Advanced NumPy Learning Guide

In [1]:
import numpy as np

## 1. Creating Advanced NumPy Arrays

In [2]:
print("--- Creating Advanced Arrays ---")
arr1 = np.arange(1, 21).reshape(4, 5)
arr2 = np.linspace(0, 1, 10)
arr3 = np.random.normal(loc=50, scale=10, size=(3,3))
print("Arange Array:\n", arr1)
print("Linspace Array:\n", arr2)
print("Random Normal Array:\n", arr3)

--- Creating Advanced Arrays ---
Arange Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Linspace Array:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Random Normal Array:
 [[49.58358088 56.06318023 36.94774497]
 [53.86672267 68.97043731 58.07201782]
 [36.55474897 20.43907345 39.84110937]]


## 2. Indexing & Slicing

In [3]:
print("\n--- Indexing & Slicing ---")
print("Element at (2,3):", arr1[2,3])
print("First row:", arr1[0, :])
print("Last column:", arr1[:, -1])


--- Indexing & Slicing ---
Element at (2,3): 14
First row: [1 2 3 4 5]
Last column: [ 5 10 15 20]


## 3. Broadcasting & Vectorized Operations

In [4]:
print("\n--- Broadcasting & Vectorized Operations ---")
arr4 = np.array([1, 2, 3])
arr5 = np.array([[1], [2], [3]])
print("Element-wise Multiplication:\n", arr4 * arr5)
print("Exponential of each element:\n", np.exp(arr4))


--- Broadcasting & Vectorized Operations ---
Element-wise Multiplication:
 [[1 2 3]
 [2 4 6]
 [3 6 9]]
Exponential of each element:
 [ 2.71828183  7.3890561  20.08553692]


## 4. Advanced Statistical Functions

In [5]:
print("\n--- Advanced Statistics ---")
data = np.random.randint(1, 100, size=(5, 5))
print("Data:\n", data)
print("Mean:", np.mean(data, axis=1))
print("Standard Deviation:", np.std(data, axis=0))
print("Median:", np.median(data))
print("Percentile (75th):", np.percentile(data, 75))


--- Advanced Statistics ---
Data:
 [[81 96 43 91 28]
 [54 36 47 56 54]
 [13 66 55 24 68]
 [ 5 19 20 18 82]
 [ 9 49 72 85 59]]
Mean: [67.8 49.4 45.2 28.8 54.8]
Standard Deviation: [30.01066477 26.37726294 16.93044595 30.08920072 17.84824921]
Median: 54.0
Percentile (75th): 68.0


## 5. Linear Algebra with NumPy

In [6]:
print("\n--- Linear Algebra ---")
matrix_a = np.array([[2, 3], [4, 5]])
matrix_b = np.array([[1, 2], [3, 4]])
print("Matrix Multiplication:\n", np.matmul(matrix_a, matrix_b))
print("Determinant of A:", np.linalg.det(matrix_a))
print("Eigenvalues of A:", np.linalg.eig(matrix_a)[0])


--- Linear Algebra ---
Matrix Multiplication:
 [[11 16]
 [19 28]]
Determinant of A: -2.0
Eigenvalues of A: [-0.27491722  7.27491722]


## 6. Performance Optimization

In [7]:
print("\n--- Performance Optimization ---")
arr_large = np.random.rand(1000000)
%timeit np.sum(arr_large)  # Optimized NumPy function
%timeit sum(arr_large)  # Slower Python loop


--- Performance Optimization ---
557 μs ± 65.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
82.2 ms ± 1.91 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## 7. Applying NumPy in Bioinformatics

In [8]:
print("\n--- NumPy in Bioinformatics ---")
dna_gc_content = np.random.randint(30, 60, size=10)
print("DNA GC Content:", dna_gc_content)
print("GC Content Mean:", np.mean(dna_gc_content))
print("Sorted GC Content:", np.sort(dna_gc_content))


--- NumPy in Bioinformatics ---
DNA GC Content: [46 39 53 39 47 51 34 58 56 55]
GC Content Mean: 47.8
Sorted GC Content: [34 39 39 46 47 51 53 55 56 58]
