### Advanced NumPy Learning Guide (Jupyter Notebook Format)

In [1]:
import numpy as np

## 1. Creating Advanced NumPy Arrays

In [2]:
print("--- Creating Advanced Arrays ---")
arr1 = np.arange(1, 21).reshape(4, 5)
arr2 = np.linspace(0, 1, 10)
arr3 = np.random.normal(loc=50, scale=10, size=(3,3))
print("Arange Array:\n", arr1)
print("Linspace Array:\n", arr2)
print("Random Normal Array:\n", arr3)

--- Creating Advanced Arrays ---
Arange Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Linspace Array:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Random Normal Array:
 [[50.61013692 70.27199355 52.0881686 ]
 [50.22718697 50.38494729 39.04191554]
 [58.45813927 48.78848297 65.01894096]]


## 2. Indexing & Slicing

In [3]:
print("\n--- Indexing & Slicing ---")
print("Element at (2,3):", arr1[2,3])
print("First row:", arr1[0, :])
print("Last column:", arr1[:, -1])


--- Indexing & Slicing ---
Element at (2,3): 14
First row: [1 2 3 4 5]
Last column: [ 5 10 15 20]


## 3. Broadcasting & Vectorized Operations

In [4]:
print("\n--- Broadcasting & Vectorized Operations ---")
arr4 = np.array([1, 2, 3])
arr5 = np.array([[1], [2], [3]])
print("Element-wise Multiplication:\n", arr4 * arr5)
print("Exponential of each element:\n", np.exp(arr4))


--- Broadcasting & Vectorized Operations ---
Element-wise Multiplication:
 [[1 2 3]
 [2 4 6]
 [3 6 9]]
Exponential of each element:
 [ 2.71828183  7.3890561  20.08553692]


## 4. Advanced Statistical Functions